### ISSUE TITLE
Filtrer les anciens Xebians

### ISSUE THREAD

**Issue by tauffredou** [xebia-france/xskillz#53]
Dans la page "Chercher un Xebian", il n'est pas possible de filtrer les anciens Xebians pour ne pas les afficher.

**Comment by jsmadja** [comment]
On doit les supprimer de la base en fait, Xav devait faire la feature :D

Le 9 février 2015 12:07, Thomas Auffredou <notifications@github.com> a
écrit :

**Comment by tauffredou** [comment]
Je trouve dommage de supprimer les données,  ça pourrait être utile.

**Comment by xbucchiotty** [comment]
Je changerai le type du Node pour plus qu'il n'apparaisse dans les
recherches...

2015-02-09 18:56 GMT+01:00 Thomas Auffredou <notifications@github.com>:

> Je trouve dommage de supprimer les données, ça pourrait être utile.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/xebia-france/xskillz/issues/53#issuecomment-73556207>.
>



-- 

Xavier Bucchiotty

[image: Xebia logo] <http://www.xebia.fr/>
« Software Development Done Right »
156, boulevard Haussmann, 75008 Paris
xbucchiotty@xebia.fr[image: Great Place To Work 2014]
<http://www.greatplacetowork.fr/>

[image: Alliance logo]

**Comment by xbucchiotty** [comment]
Mais du point de vue du droit, je ne suis pas sûr que cela est bien. Une
personne qui part n'a pas nécessairement envie que Xebia garde des
informations électroniques sur elle!

2015-02-09 19:13 GMT+01:00 Xavier Bucchiotty <xbucchiotty@xebia.fr>:

> Je changerai le type du Node pour plus qu'il n'apparaisse dans les
> recherches...
>
> 2015-02-09 18:56 GMT+01:00 Thomas Auffredou <notifications@github.com>:
>
>> Je trouve dommage de supprimer les données, ça pourrait être utile.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/xebia-france/xskillz/issues/53#issuecomment-73556207>
>> .
>>
>
>
>
> --
>
> Xavier Bucchiotty
>
> [image: Xebia logo] <http://www.xebia.fr/>
> « Software Development Done Right »
> 156, boulevard Haussmann, 75008 Paris
> xbucchiotty@xebia.fr[image: Great Place To Work 2014]
> <http://www.greatplacetowork.fr/>
>
> [image: Alliance logo]
>



-- 

Xavier Bucchiotty

[image: Xebia logo] <http://www.xebia.fr/>
« Software Development Done Right »
156, boulevard Haussmann, 75008 Paris
xbucchiotty@xebia.fr[image: Great Place To Work 2014]
<http://www.greatplacetowork.fr/>

[image: Alliance logo]

**Comment by jsmadja** [comment]
Anciens xebians supprimées
