### ISSUE TITLE
Les avatars ne correspondent plus après plusieurs recherches de skillz

### ISSUE THREAD

**Issue by jsmadja** [xebia-france/xskillz#54]

**Comment by jeremiemartinez** [comment]
Reproduction : 

Je cherche les compétences Android. Ensuite, je cherche les compétences d'Android wear. L'avatar de Thomas Auffredou se retrouve sur le profil de Thomas G.

**Comment by jsmadja** [comment]
La création de l'url gravatar est dorénavant créé par nodejs parce que la directive angular est buggée on dirait.
